% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={ANOVA analysis of frog dataset},
  pdfauthor={Thomas M Smith},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{ANOVA analysis of frog dataset}
\author{Thomas M Smith}
\date{2024-02-27}

\begin{document}
\maketitle

\hypertarget{results-from-anova}{%
\section{Results from ANOVA}\label{results-from-anova}}

\begin{verbatim}
## 
## Call:
## lm(formula = days ~ temperature, data = frog_data_clean)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##   -2.3   -1.0    0.0    0.8    2.0 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    26.3000     0.2572  102.26   <2e-16 ***
## temperature18  -5.3000     0.3637  -14.57   <2e-16 ***
## temperature25 -10.1000     0.3637  -27.77   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.15 on 57 degrees of freedom
## Multiple R-squared:  0.9312, Adjusted R-squared:  0.9288 
## F-statistic: 385.9 on 2 and 57 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{longtable}{rrrrr}
\toprule
Df & Sum Sq & Mean Sq & F value & Pr(>F) \\ 
\midrule\addlinespace[2.5pt]
2 & 1020.933 & 510.466667 & 385.8966 & 7.357304e-34 \\ 
57 & 75.400 & 1.322807 & NA & NA \\ 
\bottomrule
\end{longtable}
\begin{longtable}{lrrrrrr}
\toprule
term & estimate & std.error & statistic & p.value & conf.low & conf.high \\ 
\midrule\addlinespace[2.5pt]
(Intercept) & 26.3 & 0.2571777 & 102.26394 & 2.781059e-66 & 25.785011 & 26.814989 \\ 
temperature18 & -5.3 & 0.3637041 & -14.57228 & 7.081214e-21 & -6.028305 & -4.571695 \\ 
temperature25 & -10.1 & 0.3637041 & -27.76982 & 8.187867e-35 & -10.828305 & -9.371695 \\ 
\bottomrule
\end{longtable}

\hypertarget{putting-the-anova-test-into-words}{%
\section{Putting the ANOVA test into
words}\label{putting-the-anova-test-into-words}}

\hypertarget{increasing-enivornmental-temperatures-had-a-clear-negative-effect-on-the-time-taken-for-frogspawn-to-hatch-one-way-anova-f257-385.9-p-0.001.-at-13c-the-mean-time-to-hatching-was-26.3-days-this-decreased-by-an-average-of-5.3-days-at-18c-and-finally-by-10.1-days-at-25c.}{%
\subsubsection{Increasing enivornmental temperatures had a clear
negative effect on the time taken for frogspawn to hatch (one-way ANOVA:
F2,57 = 385.9, P \textless{} 0.001). At 13∘C the mean time to hatching
was 26.3 days, this decreased by an average of 5.3 days at 18∘C and
finally by 10.1 days at
25∘C.}\label{increasing-enivornmental-temperatures-had-a-clear-negative-effect-on-the-time-taken-for-frogspawn-to-hatch-one-way-anova-f257-385.9-p-0.001.-at-13c-the-mean-time-to-hatching-was-26.3-days-this-decreased-by-an-average-of-5.3-days-at-18c-and-finally-by-10.1-days-at-25c.}}

\hypertarget{visualised-dataset-figure-1-previously-analysed-using-anova}{%
\subsection{Visualised dataset (Figure 1) previously analysed using
ANOVA}\label{visualised-dataset-figure-1-previously-analysed-using-anova}}

\begin{center}\includegraphics[width=0.8\linewidth]{frog_data_rmd_files/figure-latex/plotting-1} \end{center}

\hypertarget{figure-1-the-time-in-days-it-takes-for-frogspawn-to-hatch-in-13-18-and-25c-temperatures.-thick-horizontal-line-is-the-median-with-individual-points-displayed-as-a-jitter.}{%
\subsubsection{Figure 1: The time in days it takes for frogspawn to
hatch in 13, 18 and 25°C temperatures. Thick horizontal line is the
median with individual points displayed as a
jitter.}\label{figure-1-the-time-in-days-it-takes-for-frogspawn-to-hatch-in-13-18-and-25c-temperatures.-thick-horizontal-line-is-the-median-with-individual-points-displayed-as-a-jitter.}}

\end{document}
